// PDF Service - Simple HTML to PDF generation
// Uses basic approach that works in serverless environments

import {
  StudentWeeklyReport,
  ActivityReport,
  GroupReport,
} from './emailReportsService'

// Generate HTML for Student Report (for PDF conversion)
export function generateStudentReportHtml(report: StudentWeeklyReport): string {
  const qualityChartData = report.qualityDistribution
    .map((q) => `Level ${q.level}: ${'█'.repeat(q.count)}${q.count > 0 ? ` (${q.count})` : ''}`)
    .join('\n')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Student Report - ${report.user.name}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }
    .stat-box { background: #f3f4f6; padding: 15px; border-radius: 8px; }
    .stat-value { font-size: 24px; font-weight: bold; color: #2563eb; }
    .stat-label { color: #6b7280; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; }
    th { background: #f3f4f6; }
    .chart { font-family: monospace; white-space: pre; background: #f9fafb; padding: 15px; border-radius: 8px; }
    .suggestion { background: #fef3c7; padding: 10px; border-left: 4px solid #f59e0b; margin: 10px 0; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📊 Student Learning Report</h1>
  <p><strong>Student:</strong> ${report.user.name}</p>
  <p><strong>Week Ending:</strong> ${report.weekEnding}</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>

  <h2>Summary Statistics</h2>
  <div class="stat-grid">
    <div class="stat-box">
      <div class="stat-value">${report.analytics.totalQuestions}</div>
      <div class="stat-label">Total Questions</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.analytics.recentQuestions}</div>
      <div class="stat-label">This Week</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.analytics.averageQuality}/5</div>
      <div class="stat-label">Avg Quality</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.weekChange > 0 ? '+' : ''}${report.weekChange}%</div>
      <div class="stat-label">Week Change</div>
    </div>
  </div>

  <h2>Quality Distribution</h2>
  <div class="chart">${qualityChartData}</div>

  <h2>Recent Questions</h2>
  <table>
    <tr><th>Date</th><th>Question</th><th>Activity</th><th>Quality</th></tr>
    ${report.recentQuestions.map((q) => `<tr><td>${q.date}</td><td>${q.question}...</td><td>${q.activityName}</td><td>${q.quality}/5</td></tr>`).join('')}
  </table>

  ${
    report.improvementSuggestions.length > 0
      ? `
  <h2>Improvement Suggestions</h2>
  ${report.improvementSuggestions.map((s) => `<div class="suggestion">💡 ${s}</div>`).join('')}
  `
      : ''
  }

  <div class="footer">
    Generated by SMILE Platform | ${new Date().toISOString()}
  </div>
</body>
</html>
  `
}

// Generate HTML for Activity Report (for PDF conversion)
export function generateActivityReportHtml(report: ActivityReport): string {
  const qualityChartData = report.qualityDistribution
    .map((q) => `Level ${q.level}: ${'█'.repeat(q.count)}${q.count > 0 ? ` (${q.count})` : ''}`)
    .join('\n')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Activity Report - ${report.activity.name}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }
    .stat-box { background: #f3f4f6; padding: 15px; border-radius: 8px; }
    .stat-value { font-size: 24px; font-weight: bold; color: #2563eb; }
    .stat-label { color: #6b7280; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; }
    th { background: #f3f4f6; }
    .chart { font-family: monospace; white-space: pre; background: #f9fafb; padding: 15px; border-radius: 8px; }
    .keywords { display: flex; flex-wrap: wrap; gap: 8px; }
    .keyword { background: #dbeafe; color: #1e40af; padding: 5px 10px; border-radius: 15px; font-size: 14px; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📚 Activity Report</h1>
  <p><strong>Activity:</strong> ${report.activity.name}</p>
  <p><strong>Subject:</strong> ${report.activity.subject || 'N/A'}</p>
  <p><strong>Owner:</strong> ${report.activity.ownerName}</p>
  <p><strong>Report Period:</strong> ${report.dateRange.start} to ${report.dateRange.end}</p>

  <h2>Summary Statistics</h2>
  <div class="stat-grid">
    <div class="stat-box">
      <div class="stat-value">${report.summary.totalStudents}</div>
      <div class="stat-label">Total Students</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.summary.totalQuestions}</div>
      <div class="stat-label">Total Questions</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.summary.avgQuality}/5</div>
      <div class="stat-label">Avg Quality</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${Math.round(report.summary.totalQuestions / Math.max(report.summary.totalStudents, 1))}</div>
      <div class="stat-label">Avg per Student</div>
    </div>
  </div>

  <h2>Quality Distribution</h2>
  <div class="chart">${qualityChartData}</div>

  <h2>Student Breakdown</h2>
  <table>
    <tr><th>Student</th><th>Questions</th><th>Avg Quality</th><th>Last Active</th></tr>
    ${report.studentBreakdown.map((s) => `<tr><td>${s.studentName}</td><td>${s.questions}</td><td>${s.avgQuality}/5</td><td>${s.lastActive}</td></tr>`).join('')}
  </table>

  <h2>Top Keywords</h2>
  <div class="keywords">
    ${report.topKeywords.map((k) => `<span class="keyword">${k.keyword} (${k.count})</span>`).join('')}
  </div>

  <div class="footer">
    Generated by SMILE Platform | ${new Date().toISOString()}
  </div>
</body>
</html>
  `
}

// Generate HTML for Group Report (for PDF conversion)
export function generateGroupReportHtml(report: GroupReport): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Group Report - ${report.group.name}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }
    .stat-box { background: #f3f4f6; padding: 15px; border-radius: 8px; }
    .stat-value { font-size: 24px; font-weight: bold; color: #2563eb; }
    .stat-label { color: #6b7280; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; }
    th { background: #f3f4f6; }
    .highlight { background: #fef3c7; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🏫 Group Report</h1>
  <p><strong>Group:</strong> ${report.group.name}</p>
  <p><strong>Owner:</strong> ${report.group.ownerName}</p>
  <p><strong>Report Period:</strong> ${report.dateRange.start} to ${report.dateRange.end}</p>

  <h2>Summary Statistics</h2>
  <div class="stat-grid">
    <div class="stat-box">
      <div class="stat-value">${report.summary.totalActivities}</div>
      <div class="stat-label">Activities</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.summary.totalStudents}</div>
      <div class="stat-label">Students</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.summary.totalQuestions}</div>
      <div class="stat-label">Questions</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${report.summary.avgQuality}/5</div>
      <div class="stat-label">Avg Quality</div>
    </div>
  </div>

  <h2>Activity Breakdown</h2>
  <table>
    <tr><th>Activity</th><th>Students</th><th>Questions</th><th>Avg Quality</th></tr>
    ${report.activityBreakdown.map((a) => `<tr><td>${a.activityName}</td><td>${a.students}</td><td>${a.questions}</td><td>${a.avgQuality}/5</td></tr>`).join('')}
  </table>

  <h2>🏆 Top Performers</h2>
  <table>
    <tr><th>Rank</th><th>Student</th><th>Questions</th><th>Avg Quality</th></tr>
    ${report.topPerformers.map((p, i) => `<tr${i < 3 ? ' class="highlight"' : ''}><td>${i + 1}</td><td>${p.studentName}</td><td>${p.questions}</td><td>${p.avgQuality}/5</td></tr>`).join('')}
  </table>

  <div class="footer">
    Generated by SMILE Platform | ${new Date().toISOString()}
  </div>
</body>
</html>
  `
}

// Generate CSV for Student Data
export function generateStudentCsv(report: StudentWeeklyReport): string {
  const headers = ['Date', 'Question', 'Activity', 'Quality']
  const rows = report.recentQuestions.map((q) =>
    [q.date, `"${q.question.replace(/"/g, '""')}"`, q.activityName, q.quality].join(',')
  )

  return [headers.join(','), ...rows].join('\n')
}

// Generate CSV for Activity Data
export function generateActivityCsv(report: ActivityReport): string {
  const headers = ['Student', 'Questions', 'Avg Quality', 'Last Active']
  const rows = report.studentBreakdown.map((s) =>
    [s.studentName, s.questions, s.avgQuality, s.lastActive].join(',')
  )

  return [headers.join(','), ...rows].join('\n')
}

// Generate CSV for Group Data
export function generateGroupCsv(report: GroupReport): string {
  const sections: string[] = []

  // Activity summary section
  sections.push('=== Activity Summary ===')
  sections.push(['Activity', 'Students', 'Questions', 'Avg Quality'].join(','))
  report.activityBreakdown.forEach((a) => {
    sections.push([a.activityName, a.students, a.questions, a.avgQuality].join(','))
  })

  sections.push('')

  // Top performers section
  sections.push('=== Top Performers ===')
  sections.push(['Student', 'Questions', 'Avg Quality'].join(','))
  report.topPerformers.forEach((p) => {
    sections.push([p.studentName, p.questions, p.avgQuality].join(','))
  })

  return sections.join('\n')
}
